services:
    # nginx
    nginx-service:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: devenv-nginx-container
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./apps:/var/www/apps
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl-params.conf:/etc/nginx/ssl-params.conf
        depends_on:
            - phplatest-service # add PHP services bellow
            - mysql8-service
        networks:
            - devenv
    # php
    phplatest-service:
        build:
            context: .
            dockerfile: docker/php/Dockerfile-latest
            args:
                # set host user UID and GID, to create non-sudo user
                UID: ${HOST_UID:-1000}
                GID: ${HOST_GID:-1000}
        container_name: devenv-phplatest-container
        volumes:
            - ./apps:/var/www/apps
            - ./php/configs/php-latest.ini:/usr/local/etc/php/php.ini
            - ./php/configs/xdebug3.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        extra_hosts:
            - host.docker.internal:${HOST_IP:-172.17.0.1}
        networks:
            - devenv
    php81-service:
        build:
            context: .
            dockerfile: docker/php/Dockerfile-php81
            args:
                # set host user UID and GID, to create non-sudo user
                UID: ${HOST_UID:-1000}
                GID: ${HOST_GID:-1000}
        container_name: devenv-php81-container
        volumes:
            - ./apps:/var/www/apps
            - ./php/configs/php-81.ini:/usr/local/etc/php/php.ini
            - ./php/configs/xdebug3.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        extra_hosts:
            - host.docker.internal:${HOST_IP:-172.17.0.1}
        networks:
            - devenv
    # node
    node-service:
        build:
            context: .
            dockerfile: docker/nodejs/Dockerfile
        container_name: devenv-node-container
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./apps:/var/www/apps
        working_dir: /var/www/apps
        networks:
            - devenv
    # mysql
    mysql8-service:
        image: mysql:8
        container_name: devenv-mysql8-container
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - devenv
    # phpMyAdmin
    phpmyadmin:
        depends_on:
            - mysql8-service
        image: phpmyadmin/phpmyadmin
        container_name: devenv-phpmyadmin
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql8-service
            - PMA_PORT=3306
        networks:
            - devenv
    # MailHog
    mailhog:
        image: mailhog/mailhog
        container_name: devenv-mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
        networks:
            - devenv

networks:
    devenv: